<?php
$title = 'Редактирование ветки';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('tree', array('action' => 'edit')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
?>
<select>
	<?php echo $this->list ?>
</select>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();